main: com.apion.hglobby.HungerGamesLobby
name: HungerGamesLobby
version: 1.0.0
commands:
  queue:
    description: Enters you into a new hunger games lobby queue
  queueother:
    description: Enters someone else into a new hunger games lobby queue
  queueall:
    description: Enters all players in the current server into a queue
